// The 20 levels. Legend: # wall, . floor, P start, G goal, D Day bridge,
// N Night bridge, 0-3 Ghost gate needing that wheel slot, ? Ghost gate (any
// slot), E Eye, M magic door.
// stars: [x, y] positions of the stars to collect (any passable tile).
// need: stars required to finish (default 2; the last level needs all 5).
// stepOn[i] is the event that completes steps[i] (select:K, skill:K, enter:T,
// eye, world:W, near:door, goal).
// Levels 11-13, 14-16 and 17-19 form three difficulty tiers (bigger mazes,
// more elements, repeated Eyes, forks); 20 is the finale.
export const LEVELS = [
  {
    id: 1,
    name: 'The Owl',
    chars: [
      'X',
    ],
    guidance: 'full',
    startActive: false,
    map: [
      '################',
      '#P.............#',
      '##############.#',
      '##############.#',
      '#G....N........#',
      '###.############',
      '################',
    ],
    stars: [[6, 1], [10, 4], [3, 5]],
    goal: 'Walk to the glowing star at the end of the maze.',
    why: 'A bridge on the way only exists at Night. The Owl flips the world with an X gate, the quantum NOT: it swaps state 0 (Day) and state 1 (Night).',
    steps: [
      'Press X to pick the Owl.',
      'Press Space to flip the world to Night.',
      'Collect stars on the way and cross the glowing bridge to the big star.',
    ],
    stepOn: [
      'select:X',
      'skill:X',
      'goal',
    ],
    hints: [],
    card: {
      text: 'The Owl flips the world between Day and Night. Flip twice and you are back where you started.',
      term: 'This is called the X gate (a quantum NOT)',
      useful: 'X is how a quantum program sets a qubit to a starting value, just like writing a 1 into a classical bit.',
      circuit: 'q0: ─X─',
    },
  },
  {
    id: 2,
    name: 'Goose and Eye',
    chars: [
      'H',
    ],
    guidance: 'full',
    startActive: false,
    map: [
      '################',
      '#P.............#',
      '##############.#',
      '##############.#',
      '#G.N.E?........#',
      '####.###########',
      '################',
    ],
    stars: [[5, 1], [10, 4], [4, 5]],
    goal: 'Make a Night bridge usable with only the Goose and the Eye.',
    why: 'The Goose (H gate) turns the world into a ghost: Day and Night at once. The Eye measures it and forces a random choice, so you may need a few tries.',
    steps: [
      'Press H to pick the Goose.',
      'Press Space to turn into a ghost.',
      'Walk through the shimmering gate onto the Eye.',
      'Night? Cross the bridge. Day? Become a ghost again and step back onto the Eye.',
    ],
    stepOn: [
      'select:H',
      'skill:H',
      'eye',
      'goal',
    ],
    hints: [],
    card: {
      text: 'The Goose puts the world in Day and Night at once. The Eye forces it to pick one, and nobody can say which.',
      term: 'This is called superposition, and the Eye is a measurement',
      useful: 'Superposition plus measurement is how a quantum computer produces an answer: many possibilities are turned into one result, with odds set by the circuit.',
      circuit: 'q0: ─H─M─',
    },
  },
  {
    id: 3,
    name: 'Return',
    chars: [
      'H',
    ],
    guidance: 'hints',
    map: [
      '################',
      '#P.............#',
      '##############.#',
      '##############.#',
      '#G..D.E.?......#',
      '###.############',
      '################',
    ],
    stars: [[7, 1], [12, 4], [3, 5]],
    goal: 'Cross the Day bridge without letting the Eye decide for you.',
    why: 'A second H undoes the first: the ghost folds back into a certain Day. Measuring the ghost instead would be a coin toss.',
    steps: [],
    hints: [
      'Think about using the Goose twice in a row. Can a ghost be undone?',
      'Look at the stretch between the shimmering gate and the Day bridge. The Eye sits there, and it decides at random if you are still a ghost when you step on it.',
      'You must be a ghost to pass the gate, but not when you reach the Eye. Undo the ghost in between, and the Eye will have nothing left to decide.',
    ],
    card: {
      text: 'Calling the Goose twice puts the world exactly back. No chance involved: the two ghost paths cancel out.',
      term: 'This is called interference (H is its own undo)',
      useful: 'Interference is the heart of quantum algorithms: you steer the amplitudes so wrong answers cancel and right answers add up.',
      circuit: 'q0: ─H─H─',
    },
  },
  {
    id: 4,
    name: 'The Lizard',
    chars: [
      'H',
      'S',
    ],
    guidance: 'full',
    map: [
      '################',
      '#P.............#',
      '##############.#',
      '##############.#',
      '#G..1..........#',
      '###.############',
      '################',
    ],
    stars: [[5, 1], [10, 4], [3, 5]],
    goal: 'Open the coloured gate by turning the ghost to the matching colour.',
    why: 'A ghost carries a hidden colour (its phase). The Lizard\'s S gate turns it a quarter. A gate only opens for its own colour.',
    steps: [
      'Press H, then Space: you become a ghost.',
      'Press S to pick the Lizard, then Space: the colour wheel turns one slot.',
      'Walk through the gate that matches the wheel.',
    ],
    stepOn: [
      'skill:H',
      'skill:S',
      'goal',
    ],
    hints: [],
    card: {
      text: 'A ghost has a hidden colour. The Lizard turns it a quarter. In Day or Night you cannot see it, but a ghost can.',
      term: 'This is called phase, and this is the S gate',
      useful: 'Phase cannot be read out directly, yet it controls interference. Algorithms such as Grover search and Shor factoring depend on it.',
      circuit: 'q0: ─H─S─',
    },
  },
  {
    id: 5,
    name: 'Two quarters',
    chars: [
      'H',
      'S',
    ],
    guidance: 'hints',
    map: [
      '################',
      '#P.............#',
      '##############.#',
      '##############.#',
      '#G.N..2........#',
      '#####.##########',
      '################',
    ],
    stars: [[5, 1], [11, 4], [5, 5]],
    goal: 'Reach Night without the Owl.',
    why: 'H S S H lands on Night for sure: two quarter turns hide a half turn, and the last H turns that hidden colour into a real change.',
    steps: [],
    hints: [
      'Night is the opposite of Day, but you have no flip. Still, a ghost\'s hidden colour can turn into a real difference when you fold the ghost back.',
      'Look at the gate: it wants the ghost colour at slot 2 on the qubit view. The Lizard moves the colour, the Goose makes and folds the ghost.',
      'Slot 2 is two quarter turns away from where a new ghost starts. Get there before the gate, then fold the ghost back and see which world you land in.',
    ],
    card: {
      text: 'Two quarter turns hide a half turn. Folding the ghost back turns that hidden colour into a real change: Night, for sure.',
      term: 'This is called a phase change showing up through interference (S then S equals Z)',
      useful: 'Gates combine: S·S = Z. Quantum compilers use identities like this to shorten circuits.',
      circuit: 'q0: ─H─S─S─H─',
    },
  },
  {
    id: 6,
    name: 'The Octopus',
    chars: [
      'H',
      'Z',
    ],
    guidance: 'full',
    map: [
      '################',
      '#P.............#',
      '##############.#',
      '##############.#',
      '#G..N.2........#',
      '###.############',
      '################',
    ],
    stars: [[5, 1], [11, 4], [3, 5]],
    goal: 'Reach Night using the Octopus instead of the Owl.',
    why: 'The Octopus (Z gate) flips the ghost\'s colour by half a turn in one move, the same as two Lizard quarters.',
    steps: [
      'Press H, then Space: you become a ghost.',
      'Press Z to pick the Octopus, then Space: a half turn in one go.',
      'Walk through the gate.',
      'Press H to pick the Goose and Space again to land in Night.',
      'Cross the bridge.',
    ],
    stepOn: [
      'skill:H',
      'skill:Z',
      'enter:2',
      'world:night',
      'goal',
    ],
    hints: [],
    card: {
      text: 'The Octopus does a half turn in one move, the same as two Lizard quarters.',
      term: 'This is called the Z gate (phase flip)',
      useful: 'Z is the phase flip, a building block of quantum error-correcting codes.',
      circuit: 'q0: ─H─Z─H─',
    },
  },
  {
    id: 7,
    name: 'No owl',
    chars: [
      'H',
      'S',
      'Z',
    ],
    guidance: 'hints',
    map: [
      '################',
      '#P..2.N........#',
      '##############.#',
      '##############.#',
      '#G.D.0.........#',
      '##.#############',
      '################',
    ],
    stars: [[9, 1], [11, 4], [2, 5]],
    goal: 'Cross a Night bridge, then come back to Day for the second bridge, with no Owl.',
    why: 'H Z H turns Day into Night, and from Night it turns Night back into Day. The gates ask for the wheel at slot 2 first, then slot 0.',
    steps: [],
    hints: [
      'Each bridge needs a different world, and nothing here flips the world directly. Gates can do it: a ghost, a turn of its colour, and a fold back.',
      'There are two gates: the first asks for colour slot 2, the second for slot 0. The Octopus gives a half turn, the Lizard a quarter. Fold back with the Goose after each gate.',
      'Before each gate, turn the colour to the slot it asks for. A new ghost starts at slot 0, but a ghost made from Night starts at slot 2, so the second gate needs a different amount of turning.',
    ],
    card: {
      text: 'The same trick works from Night too: a ghost, a half turn, and folding back takes you across to the other world.',
      term: 'This is called changing basis: H, act, H again',
      useful: 'Do H, act in the phase world, do H back. This pattern appears all over quantum algorithms.',
      circuit: 'q0: ─H─Z─H─ ... ─H─Z─H─',
    },
  },
  {
    id: 8,
    name: 'The Cat',
    chars: [
      'X',
      'C',
    ],
    guidance: 'full',
    map: [
      '################',
      '#P.............#',
      '##############.#',
      '##############.#',
      '#G..M..........#',
      '###.############',
      '################',
    ],
    stars: [[6, 1], [10, 4], [3, 5]],
    goal: 'Open the magic door with the Owl and the Cat.',
    why: 'The magic door is a second qubit. The Cat\'s CNOT gate flips the door only if the world is Night; in Day it does nothing.',
    steps: [
      'Press X, then Space: flip to Night.',
      'Walk next to the magic door.',
      'Press C to pick the Cat, then Space: link the door to the world.',
      'Walk through the open door.',
    ],
    stepOn: [
      'skill:X',
      'near:door',
      'skill:C',
      'goal',
    ],
    hints: [],
    card: {
      text: 'The Cat links the door to the world: if it is Night, the door flips. In Day nothing happens.',
      term: 'This is called the CNOT gate (controlled NOT)',
      useful: 'CNOT links two qubits. It is the building block of every multi-qubit circuit.',
      circuit: 'q0: ─X─●─\nq1: ───⊕─',
    },
  },
  {
    id: 9,
    name: 'Magic door',
    chars: [
      'H',
      'C',
    ],
    guidance: 'hints',
    map: [
      '################',
      '#P.............#',
      '##############.#',
      '##############.#',
      '#G..M..........#',
      '#####E##.#######',
      '################',
    ],
    stars: [[6, 1], [11, 4], [8, 5]],
    goal: 'Open the door by letting the Eye choose: you need Night and open.',
    why: 'H then CNOT makes the world and the door share one fate (entanglement): either Night and open, or Day and closed, never mixed.',
    steps: [],
    hints: [
      'The door can only open together with the world. Think about linking the two while the world is still a ghost, then forcing a result.',
      'Stand on the tile next to the door. The Eye in the small alcove below is what forces the result, so the link has to happen before you step on it.',
      'The Eye gives one of two outcomes: Night with the door open (go through), or Day with the door closed. If you get the second, you have to link again from a fresh ghost.',
    ],
    card: {
      text: 'World and door now share one fate: either Night and open, or Day and closed, never mixed. Looking at one tells you the other.',
      term: 'This is called entanglement',
      useful: 'Entanglement powers quantum teleportation, quantum key distribution and many algorithm speed-ups.',
      circuit: 'q0: ─H─●─M─\nq1: ───⊕─M─',
    },
  },
  {
    id: 10,
    name: 'Halfway',
    chars: [
      'X',
      'H',
      'S',
      'Z',
      'C',
    ],
    guidance: 'none',
    map: [
      '################',
      '#P..1.N........#',
      '###.##########.#',
      '##############.#',
      '#.....M........#',
      '#.##############',
      '#.##############',
      '#..0.D.......G.#',
      '################',
    ],
    stars: [[3, 2], [10, 4], [8, 7]],
    goal: 'Use everything you know: two quarters, a key and a half turn.',
    why: 'A real quantum program chains gates: phase tricks to reach Night, a controlled gate to open the door, and a half turn to come back to Day.',
    steps: [],
    hints: [],
    card: {
      text: 'You used a ghost, a hidden colour, a linked door and a half turn. Every quantum program is built from small gates like these.',
      term: 'This is called a quantum circuit',
      useful: 'Complexity in quantum computing comes from combining simple gates, not from complicated ones.',
      circuit: 'q0: ─H─S─S─H─●─H─Z─H─\nq1: ─────────⊕───────',
    },
  },
  {
    id: 11,
    name: 'Fork in the Road',
    chars: [
      'X',
      'H',
      'S',
      'Z',
      'C',
    ],
    guidance: 'hints',
    startActive: false,
    map: [
      '################',
      '#P...N.........#',
      '########?#####.#',
      '########D#####M#',
      '#..N.E?........#',
      '#.##############',
      '#.##############',
      '#.....D...M.G..#',
      '###.############',
      '################',
    ],
    stars: [[14, 2], [8, 2], [3, 8]],
    goal: 'Take either road to the second corridor: through the door or through the ghost gate. Then win the Eye and finish.',
    why: 'Different gate sequences reach the same place. A road through the door needs the Cat at Night; the road through the gate needs a ghost that folds back to Day.',
    steps: [],
    hints: [
      'There are two ways down to the second corridor. Each one asks for a different state of the world.',
      'The door on the right needs the Cat and Night. The gate in the middle needs a ghost, and the bridge under it needs Day.',
      'You can check out the door road: Night first (the first bridge needs it), then link. For the gate road you must become a ghost and fold back to Day before the bridge. After the second corridor you have an Eye, then a Day bridge and another door.',
    ],
    card: {
      text: 'There was more than one correct circuit. Different gate sequences can give the same result, and a quantum compiler looks for the shortest.',
      term: 'This is called circuit optimization',
      useful: 'Fewer gates means fewer chances for errors on real quantum hardware, so shorter circuits matter.',
      circuit: 'q0: ─X─●─ or ─X─X─H─H─\nq1: ───⊕─',
    },
  },
  {
    id: 12,
    name: 'The Long Way Down',
    chars: [
      'X',
      'H',
      'S',
      'Z',
      'C',
    ],
    guidance: 'hints',
    startActive: false,
    map: [
      '##############.#',
      '#P...N.?E.D.M..#',
      '##############.#',
      '#.......M.0.D..#',
      '#.##############',
      '#..3.2.1.0....G#',
      '##########.#####',
      '################',
    ],
    stars: [[14, 0], [10, 6], [3, 1]],
    goal: 'Open the door, then walk down the colour ladder: gates 3, 2, 1, 0.',
    why: 'Phase is circular: after four quarter turns you are back where you started. So to go from colour 3 to colour 2 you must turn three quarters forward, not one back.',
    steps: [],
    hints: [
      'Colours only turn one way, a quarter at a time. Going down one step means going almost all the way round.',
      'The last corridor is a ladder: 3, 2, 1, 0. Check how many quarter turns lie between two neighbouring gates, and which character gives a half turn.',
      'Between two gates of the ladder you need three quarter turns (a half turn plus a quarter does it). Arrive at the ladder as a ghost and fold back only after the last gate.',
    ],
    card: {
      text: 'Phase is circular: four quarter turns make a full turn, which is the same as no turn. Going down a step is the same as going three steps up.',
      term: 'This is called phase being periodic (360° equals 0°)',
      useful: 'Quantum algorithms add up rotations of phase with great precision. The quantum Fourier transform, a core part of Shor\'s algorithm, is built from many such rotations.',
      circuit: 'q0: ─H─S─S─S─',
    },
  },
  {
    id: 13,
    name: 'Guarded Door',
    chars: [
      'X',
      'H',
      'S',
      'Z',
      'C',
    ],
    guidance: 'hints',
    startActive: false,
    map: [
      '####.###########',
      '#P.0.1.2.3.....#',
      '##############.#',
      '#.N.E?..0.3.D..#',
      '#.##############',
      '#..E?M.2.1.3.DG#',
      '######.#########',
      '################',
    ],
    stars: [[4, 0], [6, 6], [14, 3]],
    goal: 'Open a door whose neighbouring tile only a ghost can stand on, then climb the ladder after it.',
    why: 'Because only a ghost can stand next to the door, you must link the door to the world while the world is in superposition. That entangles them, and the Eye has to settle both.',
    steps: [],
    hints: [
      'The tile beside the door is a ghost gate. So the Cat has to act while the world is a ghost, not while it is Night.',
      'Look at the third corridor: an Eye, then the gate, then the door. The Eye is what turns the link into a definite result.',
      'Become a ghost, stand on the gate next to the door and link, then step back onto the Eye. You want the door open. If it ended up closed, make a fresh ghost and link again.',
    ],
    card: {
      text: 'Linking a ghost to the door made the two share one outcome: Night with the door open, or Day with it closed. Measuring one told you the other.',
      term: 'This is called entanglement',
      useful: 'Entanglement is a key resource in quantum teleportation, quantum cryptography and many quantum algorithms.',
      circuit: 'q0: ─H─●─M─\nq1: ───⊕─M─',
    },
  },
  {
    id: 14,
    name: 'Three Tosses',
    chars: [
      'X',
      'H',
      'S',
      'Z',
      'C',
    ],
    guidance: 'hints',
    startActive: false,
    map: [
      '############.###',
      '#P.1.N.?E.D....#',
      '##############.#',
      '#......N.E3.1..#',
      '#.##############',
      '#..?E.N.0.D....#',
      '##############.#',
      '#G.......N..D..#',
      '##########.#####',
      '################',
    ],
    stars: [[12, 0], [10, 8], [4, 1]],
    goal: 'Get through three Eye sections. After each Eye you need a particular world for the bridge that follows.',
    why: 'A measurement result is random, but you can act on it afterwards: flip with the X gate, or make a new ghost. Choose the cheapest repair.',
    steps: [],
    hints: [
      'The Eye gives a random world. You do not have to win the toss: other gates can repair a bad result.',
      'Look at the bridge after each Eye. It tells you which world you need. The Owl flips, and the Goose makes a new ghost.',
      'In the second corridor two colour gates sit in a row (1 then 3), so turn the colour between them. After every Eye, look at the bridge and repair the world instead of walking back.',
    ],
    card: {
      text: 'Measurement results are random, so a quantum program often repairs or repeats. The skill is choosing the cheapest fix.',
      term: 'This is called probabilistic computation',
      useful: 'Many quantum algorithms give the right answer only with some probability, so they are run again, or corrected, until the result is good.',
      circuit: 'q0: ─H─M─X─',
    },
  },
  {
    id: 15,
    name: 'Spiral of Colours',
    chars: [
      'X',
      'H',
      'S',
      'Z',
      'C',
    ],
    guidance: 'hints',
    startActive: false,
    map: [
      '###########.####',
      '#P.0.1.3.?E.N..#',
      '##############.#',
      '#0.1.2.3.N.E?..#',
      '#.##############',
      '#..2.1.?E.D.3..#',
      '##############.#',
      '#G....D..N.E?..#',
      '#######.########',
      '################',
    ],
    stars: [[11, 0], [7, 8], [2, 1]],
    goal: 'Four colour sections: climbing gates, a falling ladder, and Eyes. After every Eye the next bridge needs the right world.',
    why: 'Each gate checks the ghost\'s phase. Rising gates need quarter turns, falling gates need three. Every Eye then destroys the superposition, so you start again from a fresh ghost.',
    steps: [],
    hints: [
      'Look at which way the numbers go in each corridor. Rising numbers are cheap to reach; falling numbers are not.',
      'In the corridor with 3, 2, 1, 0 the colour must move forward three quarters between gates. The Octopus plus the Lizard make three quarters in two presses.',
      'Treat each corridor the same way: become a ghost, turn the colour for each gate in order, then fold back or look with the Eye. Check which bridge comes next so you end in the right world.',
    ],
    card: {
      text: 'Each Eye ended the superposition, and each new ghost started again from a clean state. Measurement resets what you can do next.',
      term: 'This is called measurement collapse',
      useful: 'After a measurement the qubit is in a definite state, which is why quantum programs usually measure at the end, or only when they need a result.',
      circuit: 'q0: ─H─S─S─S─M─H─S─M─',
    },
  },
  {
    id: 16,
    name: 'Hall of Doors',
    chars: [
      'X',
      'H',
      'S',
      'Z',
      'C',
    ],
    guidance: 'hints',
    startActive: false,
    map: [
      '####.###########',
      '#P.1.N.?E.D....#',
      '##############.#',
      '#..D..N.2.M?E..#',
      '#.##############',
      '#..?E.N.0.D....#',
      '##############.#',
      '#G.3.0.1.N.E?..#',
      '####.###########',
      '################',
    ],
    stars: [[4, 0], [4, 8], [2, 3]],
    goal: 'Open the guarded door in the second corridor, then finish three more Eye sections and a ladder.',
    why: 'The door can only be opened as part of a ghost link. Once it is open it stays open, so the rest of the level is about the world and its colour.',
    steps: [],
    hints: [
      'A ghost gate guards the door, so the door has to be opened as part of a link with a ghost.',
      'In the second corridor an Eye, a gate and the door sit in a row. The Eye is beside the gate: use it to settle the link, then go through the door.',
      'Make a ghost, link on the gate beside the door, step back to the Eye. If the door is closed, repeat from a new ghost. After the door, a colour gate and two bridges follow, then Eyes with bridges and a final ladder.',
    ],
    card: {
      text: 'Once opened, the door stays open: its qubit keeps its value while you work on the world qubit.',
      term: 'This is called keeping state in a separate qubit',
      useful: 'A quantum computer can store a result in one qubit while it keeps manipulating others, as long as it avoids disturbing the stored qubit.',
      circuit: 'q0: ─H─●─M─\nq1: ───⊕─M─',
    },
  },
  {
    id: 17,
    name: 'Round the Clock',
    chars: [
      'X',
      'H',
      'S',
      'Z',
      'C',
    ],
    guidance: 'hints',
    startActive: false,
    map: [
      '######.#########',
      '#P.1.0.3.2.....#',
      '##############.#',
      '#..D..N.2.M?E..#',
      '#.##############',
      '#..3.2.1.0.D...#',
      '##############.#',
      '#G.3.1.D.N.E?..#',
      '########.#######',
      '################',
    ],
    stars: [[6, 0], [8, 8], [4, 3]],
    goal: 'Two ladders, a guarded door and an Eye. Plan the colour and the world at every step.',
    why: 'Longer circuits combine every idea: phase counting, entanglement and measurement. Each one must leave the qubit in the right state for the next.',
    steps: [],
    hints: [
      'Plan ahead: each section ends with a state that the next section must accept.',
      'The first corridor is a ladder 1, 0, 3, 2. The third is a falling ladder 3, 2, 1, 0. The second hides a door with an Eye next to it.',
      'Count quarter turns between neighbouring gates before pressing anything. At the door: ghost, link, Eye. The last corridor mixes an Eye and a bridge with two more colour gates.',
    ],
    card: {
      text: 'This circuit chained phase counting, entanglement and measurement, each leaving the qubit in the state the next stage needed.',
      term: 'This is called composing a quantum circuit',
      useful: 'Real algorithms are long chains of simple gates, and good programmers keep track of the state between stages.',
      circuit: 'q0: ─H─S─S─S─H─●─M─',
    },
  },
  {
    id: 18,
    name: 'Maze of Phases',
    chars: [
      'X',
      'H',
      'S',
      'Z',
      'C',
    ],
    guidance: 'hints',
    startActive: false,
    map: [
      '########.#######',
      '#P.0.3.2.1.?E.N#',
      '##############.#',
      '#.N.1.0.M?E.D..#',
      '#.##############',
      '#..1.3.2.0.N...#',
      '##############.#',
      '#G..D.0.1.2.3..#',
      '#########.######',
      '################',
    ],
    stars: [[8, 0], [9, 8], [11, 7]],
    goal: 'Climb a ladder, win an Eye, open the guarded door, then descend two more ladders.',
    why: 'Descending phases are costly and Eyes reset you, so the order of operations matters. Think about the whole level before you move.',
    steps: [],
    hints: [
      'This level repeats ladders. The cost is in counting turns, not in the puzzle ideas.',
      'The first ladder reads 0, 3, 2, 1 and the others fall too. Each step down is three quarters up. The Octopus gives two of them at once.',
      'Do each ladder as one block: become a ghost, press the turns for the first gate, walk, press for the next, and so on. At the door the same ghost, link and Eye as before.',
    ],
    card: {
      text: 'Phase accumulates additively, but only a full circle brings it back. Careful bookkeeping of turns is what quantum programming looks like.',
      term: 'This is called phase accumulation',
      useful: 'Quantum algorithms such as phase estimation read off a number by measuring how much phase has built up.',
      circuit: 'q0: ─H─S─S─S─S─S─S─S─H─',
    },
  },
  {
    id: 19,
    name: 'Noise',
    chars: [
      'X',
      'H',
      'S',
      'Z',
      'C',
    ],
    guidance: 'hints',
    startActive: false,
    chase: {
      every: 2,
      delay: 6,
    },
    chasers: [[1, 1]],
    map: [
      '#############.##',
      '#P.0.3.2.1.?E.N#',
      '##############.#',
      '#0.1.2.3.N.E?..#',
      '#.##############',
      '#..E?M.3.2.1.0.#',
      '##############.#',
      '#G..N.1.2.3.0..#',
      '###########.####',
      '################',
    ],
    stars: [[13, 0], [11, 8], [10, 1]],
    goal: 'Keep moving! The Noise follows you and restarts the level if it catches you. Skills and thinking cost no time.',
    why: 'The Noise stands for decoherence: stray disturbances from the environment that destroy a qubit\'s quantum behaviour. Quantum computers have to finish before it arrives.',
    steps: [],
    hints: [
      'The Noise only moves when you move. Pressing skill keys and planning cost nothing.',
      'Walking back to retry an Eye brings you closer to the Noise. Repair a bad result with a skill (the Owl flips, the Goose folds) rather than walking back whenever you can.',
      'Plan each corridor before you step into it. Stay ahead: the Noise takes one step for every two of yours, after the first few moves.',
    ],
    card: {
      text: 'Noise from the environment can destroy a quantum state. Real quantum computers fight it with fast gates, isolation from the world, and error correction.',
      term: 'This is called decoherence',
      useful: 'Decoherence is the main obstacle to building large quantum computers, and the reason error correction is so important.',
      circuit: 'q0: ─H─S─S─S─H─M─ (before the noise arrives)',
    },
  },
  {
    id: 20,
    name: 'Grand Finale',
    chars: [
      'X',
      'H',
      'S',
      'Z',
      'C',
    ],
    guidance: 'none',
    need: 5,
    startActive: false,
    chase: {
      every: 1,
      delay: 12,
    },
    chasers: [[1, 1]],
    map: [
      '######.#####.###',
      '#P.3.2.1.0.....#',
      '##############.#',
      '#.N.1.0.M?E.D..#',
      '#.##############',
      '#..1.0.3.2.?E.N#',
      '##############.#',
      '#G..N.1.2.3.0..#',
      '###.#########.##',
      '################',
    ],
    stars: [[12, 0], [6, 0], [13, 8], [3, 8], [4, 5]],
    goal: 'Collect all 5 stars and reach the finish before the Noise catches you.',
    why: 'This last maze uses every mechanic, and the Noise is as fast as you.',
    steps: [],
    hints: [],
    card: {
      text: 'You collected every star and used all five gates against the clock. Prepare, evolve, measure, and do it before the noise wins.',
      term: 'This is called a quantum circuit: gates that prepare, evolve and measure qubits',
      useful: 'You now know the vocabulary of quantum computing: superposition, phase, interference, entanglement, measurement and decoherence.',
      circuit: 'q0: ─H─S─S─S─H─●─M─H─Z─H─\nq1: ─────────⊕─M───────',
    },
  },
];
