// The 20 levels. Legend: # wall, . floor, P start, G goal, D Day bridge,
// N Night bridge, 0-3 Ghost gate needing that wheel slot, ? Ghost gate (any
// slot), E Eye, M magic door.
// stars: [x, y] positions of the stars to collect (any passable tile).
// need: stars required to finish (default 2; the last level needs all 5).
// stepOn[i] is the event that completes steps[i] (select:K, skill:K, enter:T,
// eye, world:W, near:door, goal).
// Levels 11-13, 14-16 and 17-19 form three difficulty tiers (bigger mazes,
// more elements, repeated Eyes, forks); 20 is the finale.
export const LEVELS = [
  {
    id: 1,
    name: 'The Owl',
    chars: [
      'X',
    ],
    guidance: 'full',
    startActive: false,
    map: [
      '################',
      '#P.............#',
      '##############.#',
      '##############.#',
      '#G....N........#',
      '###.############',
      '################',
    ],
    stars: [[6, 1], [10, 4], [3, 5]],
    goal: 'Walk to the glowing star at the end of the maze.',
    why: 'A bridge on the way only exists at Night. The Owl flips the world with an X gate, the quantum NOT: it swaps state 0 (Day) and state 1 (Night).',
    steps: [
      'Press X to pick the Owl.',
      'Press Space to flip the world to Night.',
      'Collect stars on the way and cross the glowing bridge to the big star.',
    ],
    stepOn: [
      'select:X',
      'skill:X',
      'goal',
    ],
    hints: [],
    card: {
      text: 'The Owl flips the world between Day and Night. Flip twice and you are back where you started.',
      term: 'This is called the X gate (a quantum NOT)',
      useful: 'X is how a quantum program sets a qubit to a starting value, just like writing a 1 into a classical bit.',
      circuit: 'q0: ─X─',
    },
  },
  {
    id: 2,
    name: 'Goose and Eye',
    chars: [
      'H',
    ],
    guidance: 'full',
    startActive: false,
    map: [
      '################',
      '#P.............#',
      '##############.#',
      '##############.#',
      '#G.N.E?........#',
      '####.###########',
      '################',
    ],
    stars: [[5, 1], [10, 4], [4, 5]],
    goal: 'Make a Night bridge usable with only the Goose and the Eye.',
    why: 'The Goose (H gate) turns the world into a ghost: Day and Night at once. The Eye measures it and forces a random choice, so you may need a few tries.',
    steps: [
      'Press H to pick the Goose.',
      'Press Space to turn into a ghost.',
      'Walk through the shimmering gate onto the Eye.',
      'Night? Cross the bridge. Day? Become a ghost again and step back onto the Eye.',
    ],
    stepOn: [
      'select:H',
      'skill:H',
      'eye',
      'goal',
    ],
    hints: [],
    card: {
      text: 'The Goose puts the world in Day and Night at once. The Eye forces it to pick one, and nobody can say which.',
      term: 'This is called superposition, and the Eye is a measurement',
      useful: 'Superposition plus measurement is how a quantum computer produces an answer: many possibilities are turned into one result, with odds set by the circuit.',
      circuit: 'q0: ─H─M─',
    },
  },
  {
    id: 3,
    name: 'Return',
    chars: [
      'H',
    ],
    guidance: 'hints',
    map: [
      '################',
      '#P.............#',
      '##############.#',
      '##############.#',
      '#G..D.E.?......#',
      '###.############',
      '################',
    ],
    stars: [[7, 1], [12, 4], [3, 5]],
    goal: 'Cross the Day bridge without letting the Eye decide for you.',
    why: 'A second H undoes the first: the ghost folds back into a certain Day. Measuring the ghost instead would be a coin toss.',
    steps: [],
    hints: [
      'Think about using the Goose twice in a row. Can a ghost be undone?',
      'Look at the stretch between the shimmering gate and the Day bridge. The Eye sits there, and it decides at random if you are still a ghost when you step on it.',
      'You must be a ghost to pass the gate, but not when you reach the Eye. Undo the ghost in between, and the Eye will have nothing left to decide.',
    ],
    card: {
      text: 'Calling the Goose twice puts the world exactly back. No chance involved: the two ghost paths cancel out.',
      term: 'This is called interference (H is its own undo)',
      useful: 'Interference is the heart of quantum algorithms: you steer the amplitudes so wrong answers cancel and right answers add up.',
      circuit: 'q0: ─H─H─',
    },
  },
  {
    id: 4,
    name: 'The Lizard',
    chars: [
      'H',
      'S',
    ],
    guidance: 'full',
    map: [
      '################',
      '#P.............#',
      '##############.#',
      '##############.#',
      '#G..1..........#',
      '###.############',
      '################',
    ],
    stars: [[5, 1], [10, 4], [3, 5]],
    goal: 'Open the coloured gate by turning the ghost to the matching colour.',
    why: 'A ghost carries a hidden colour (its phase). The Lizard\'s S gate turns it a quarter. A gate only opens for its own colour.',
    steps: [
      'Press H, then Space: you become a ghost.',
      'Press S to pick the Lizard, then Space: the colour wheel turns one slot.',
      'Walk through the gate that matches the wheel.',
    ],
    stepOn: [
      'skill:H',
      'skill:S',
      'goal',
    ],
    hints: [],
    card: {
      text: 'A ghost has a hidden colour. The Lizard turns it a quarter. In Day or Night you cannot see it, but a ghost can.',
      term: 'This is called phase, and this is the S gate',
      useful: 'Phase cannot be read out directly, yet it controls interference. Algorithms such as Grover search and Shor factoring depend on it.',
      circuit: 'q0: ─H─S─',
    },
  },
  {
    id: 5,
    name: 'Two quarters',
    chars: [
      'H',
      'S',
    ],
    guidance: 'hints',
    map: [
      '################',
      '#P.............#',
      '##############.#',
      '##############.#',
      '#G.N..2........#',
      '#####.##########',
      '################',
    ],
    stars: [[5, 1], [11, 4], [5, 5]],
    goal: 'Reach Night without the Owl.',
    why: 'H S S H lands on Night for sure: two quarter turns hide a half turn, and the last H turns that hidden colour into a real change.',
    steps: [],
    hints: [
      'Night is the opposite of Day, but you have no flip. Still, a ghost\'s hidden colour can turn into a real difference when you fold the ghost back.',
      'Look at the gate: it wants the ghost colour at slot 2 on the qubit view. The Lizard moves the colour, the Goose makes and folds the ghost.',
      'Slot 2 is two quarter turns away from where a new ghost starts. Get there before the gate, then fold the ghost back and see which world you land in.',
    ],
    card: {
      text: 'Two quarter turns hide a half turn. Folding the ghost back turns that hidden colour into a real change: Night, for sure.',
      term: 'This is called a phase change showing up through interference (S then S equals Z)',
      useful: 'Gates combine: S·S = Z. Quantum compilers use identities like this to shorten circuits.',
      circuit: 'q0: ─H─S─S─H─',
    },
  },
  {
    id: 6,
    name: 'The Octopus',
    chars: [
      'H',
      'Z',
    ],
    guidance: 'full',
    map: [
      '################',
      '#P.............#',
      '##############.#',
      '##############.#',
      '#G..N.2........#',
      '###.############',
      '################',
    ],
    stars: [[5, 1], [11, 4], [3, 5]],
    goal: 'Reach Night using the Octopus instead of the Owl.',
    why: 'The Octopus (Z gate) flips the ghost\'s colour by half a turn in one move, the same as two Lizard quarters.',
    steps: [
      'Press H, then Space: you become a ghost.',
      'Press Z to pick the Octopus, then Space: a half turn in one go.',
      'Walk through the gate.',
      'Press H to pick the Goose and Space again to land in Night.',
      'Cross the bridge.',
    ],
    stepOn: [
      'skill:H',
      'skill:Z',
      'enter:2',
      'world:night',
      'goal',
    ],
    hints: [],
    card: {
      text: 'The Octopus does a half turn in one move, the same as two Lizard quarters.',
      term: 'This is called the Z gate (phase flip)',
      useful: 'Z is the phase flip, a building block of quantum error-correcting codes.',
      circuit: 'q0: ─H─Z─H─',
    },
  },
  {
    id: 7,
    name: 'No owl',
    chars: [
      'H',
      'S',
      'Z',
    ],
    guidance: 'hints',
    map: [
      '################',
      '#P..2.N........#',
      '##############.#',
      '##############.#',
      '#G.D.0.........#',
      '##.#############',
      '################',
    ],
    stars: [[9, 1], [11, 4], [2, 5]],
    goal: 'Cross a Night bridge, then come back to Day for the second bridge, with no Owl.',
    why: 'H Z H turns Day into Night, and from Night it turns Night back into Day. The gates ask for the wheel at slot 2 first, then slot 0.',
    steps: [],
    hints: [
      'Each bridge needs a different world, and nothing here flips the world directly. Gates can do it: a ghost, a turn of its colour, and a fold back.',
      'There are two gates: the first asks for colour slot 2, the second for slot 0. The Octopus gives a half turn, the Lizard a quarter. Fold back with the Goose after each gate.',
      'Before each gate, turn the colour to the slot it asks for. A new ghost starts at slot 0, but a ghost made from Night starts at slot 2, so the second gate needs a different amount of turning.',
    ],
    card: {
      text: 'The same trick works from Night too: a ghost, a half turn, and folding back takes you across to the other world.',
      term: 'This is called changing basis: H, act, H again',
      useful: 'Do H, act in the phase world, do H back. This pattern appears all over quantum algorithms.',
      circuit: 'q0: ─H─Z─H─ ... ─H─Z─H─',
    },
  },
  {
    id: 8,
    name: 'The Cat',
    chars: [
      'X',
      'C',
    ],
    guidance: 'full',
    map: [
      '################',
      '#P.............#',
      '##############.#',
      '##############.#',
      '#G..M..........#',
      '###.############',
      '################',
    ],
    stars: [[6, 1], [10, 4], [3, 5]],
    goal: 'Open the magic door with the Owl and the Cat.',
    why: 'The magic door is a second qubit. The Cat\'s CNOT gate flips the door only if the world is Night; in Day it does nothing.',
    steps: [
      'Press X, then Space: flip to Night.',
      'Walk next to the magic door.',
      'Press C to pick the Cat, then Space: link the door to the world.',
      'Walk through the open door.',
    ],
    stepOn: [
      'skill:X',
      'near:door',
      'skill:C',
      'goal',
    ],
    hints: [],
    card: {
      text: 'The Cat links the door to the world: if it is Night, the door flips. In Day nothing happens.',
      term: 'This is called the CNOT gate (controlled NOT)',
      useful: 'CNOT links two qubits. It is the building block of every multi-qubit circuit.',
      circuit: 'q0: ─X─●─\nq1: ───⊕─',
    },
  },
  {
    id: 9,
    name: 'Magic door',
    chars: [
      'H',
      'C',
    ],
    guidance: 'hints',
    map: [
      '################',
      '#P.............#',
      '##############.#',
      '##############.#',
      '#G..M..........#',
      '#####E##.#######',
      '################',
    ],
    stars: [[6, 1], [11, 4], [8, 5]],
    goal: 'Open the door by letting the Eye choose: you need Night and open.',
    why: 'H then CNOT makes the world and the door share one fate (entanglement): either Night and open, or Day and closed, never mixed.',
    steps: [],
    hints: [
      'The door can only open together with the world. Think about linking the two while the world is still a ghost, then forcing a result.',
      'Stand on the tile next to the door. The Eye in the small alcove below is what forces the result, so the link has to happen before you step on it.',
      'The Eye gives one of two outcomes: Night with the door open (go through), or Day with the door closed. If you get the second, you have to link again from a fresh ghost.',
    ],
    card: {
      text: 'World and door now share one fate: either Night and open, or Day and closed, never mixed. Looking at one tells you the other.',
      term: 'This is called entanglement',
      useful: 'Entanglement powers quantum teleportation, quantum key distribution and many algorithm speed-ups.',
      circuit: 'q0: ─H─●─M─\nq1: ───⊕─M─',
    },
  },
  {
    id: 10,
    name: 'Halfway',
    chars: [
      'X',
      'H',
      'S',
      'Z',
      'C',
    ],
    guidance: 'none',
    map: [
      '################',
      '#P..1.N........#',
      '###.##########.#',
      '##############.#',
      '#.....M........#',
      '#.##############',
      '#.##############',
      '#..0.D.......G.#',
      '################',
    ],
    stars: [[3, 2], [10, 4], [8, 7]],
    goal: 'Use everything you know: two quarters, a key and a half turn.',
    why: 'A real quantum program chains gates: phase tricks to reach Night, a controlled gate to open the door, and a half turn to come back to Day.',
    steps: [],
    hints: [],
    card: {
      text: 'You used a ghost, a hidden colour, a linked door and a half turn. Every quantum program is built from small gates like these.',
      term: 'This is called a quantum circuit',
      useful: 'Complexity in quantum computing comes from combining simple gates, not from complicated ones.',
      circuit: 'q0: ─H─S─S─H─●─H─Z─H─\nq1: ─────────⊕───────',
    },
  },
  {
    id: 11,
    name: 'Flip Flop',
    chars: [
      'X',
    ],
    guidance: 'hints',
    map: [
      '################',
      '#P..N..D.......#',
      '##############.#',
      '##############.#',
      '#G.N.D...N.....#',
      '############.###',
      '################',
    ],
    stars: [[7, 1], [9, 4], [12, 5]],
    goal: 'Alternate Night and Day bridges using only the Owl.',
    why: 'Each X flips the world; two flips cancel (X·X = nothing). Flip before every bridge to match it.',
    steps: [],
    hints: [
      'Idea: bridges alternate. Flip the world before each one.',
      'Only the Owl is here.',
      'Space before each bridge: a Night bridge needs Night, a Day bridge needs Day.',
    ],
    card: {
      text: 'Every flip can be undone by flipping again. Quantum gates are reversible, which is why a circuit can run backwards.',
      term: 'This is called reversibility (X is its own inverse)',
      useful: 'Reversibility is why quantum computers lose no information inside a circuit; only measurement destroys it.',
      circuit: 'q0: ─X─X─X─X─',
    },
  },
  {
    id: 12,
    name: 'Colour Ladder',
    chars: [
      'H',
      'S',
    ],
    guidance: 'hints',
    map: [
      '################',
      '#P.0.1.2.N.....#',
      '##############.#',
      '##############.#',
      '#G.D..0........#',
      '####.###########',
      '################',
    ],
    stars: [[5, 1], [12, 4], [4, 5]],
    goal: 'Climb the ladder of coloured gates, then fold back to Night; later return to Day.',
    why: 'Each S turns the wheel one quarter, and each gate checks the colour in order. A final H turns the phase into a certain world.',
    steps: [],
    hints: [
      'Idea: turn the wheel one quarter between gates, then fold back.',
      'Goose, then Lizard. The Lizard does every turn.',
      'H, gate 0, S, gate 1, S, gate 2, H (Night). Later: H, S S, gate 0, H (Day).',
    ],
    card: {
      text: 'Phase works like a counter: each quarter turn adds one, and a gate can check the count.',
      term: 'This is called accumulating phase',
      useful: 'The quantum Fourier transform, behind Shor\'s factoring, works by adding up many small phase turns.',
      circuit: 'q0: ─H─S─S─H─',
    },
  },
  {
    id: 13,
    name: 'Door in Daylight',
    chars: [
      'X',
      'C',
    ],
    guidance: 'hints',
    map: [
      '################',
      '#P....N...M.D..#',
      '##############.#',
      '##############.#',
      '#G..M..N.......#',
      '############.###',
      '################',
    ],
    stars: [[11, 1], [7, 4], [12, 5]],
    goal: 'Open the door at Night, go back to Day and walk through it.',
    why: 'The door is qubit 1. It stays open after the world changes, because CNOT only acts at the moment you use it.',
    steps: [],
    hints: [
      'Idea: the door stays open once opened. Open it at Night, then go back to Day.',
      'The Owl changes the world, the Cat opens the door.',
      'X, cross the bridge, stand next to the door, C, X (Day), go through and cross the Day bridge. Later flip to Night for the last bridge.',
    ],
    card: {
      text: 'The door kept its state while the world changed. Each qubit holds its own value until a gate acts on it.',
      term: 'This is called qubit memory: a qubit keeps its state',
      useful: 'A quantum program can store a result in one qubit while it keeps working on another.',
      circuit: 'q0: ─X─●─X─\nq1: ───⊕───',
    },
  },
  {
    id: 14,
    name: 'Triple Eye',
    chars: [
      'H',
    ],
    guidance: 'hints',
    map: [
      '################',
      '#P..?E.N.......#',
      '########.#####.#',
      '##############.#',
      '#...D.E?.......#',
      '#.##.###########',
      '#.##############',
      '#..?E.N.....G..#',
      '################',
    ],
    stars: [[11, 1], [8, 2], [4, 5]],
    goal: 'Win three coin tosses in a row: Night, then Day, then Night.',
    why: 'Each Eye measures a fresh ghost. Losing a toss is fine: become a ghost again and step back onto the Eye.',
    steps: [],
    hints: [
      'Idea: each Eye is a coin toss. Lose, and try again.',
      'Only the Goose is needed. Become a ghost, pass the gate, step on the Eye.',
      'H, gate, Eye. Wrong world? H, step back through the gate, Eye again.',
    ],
    card: {
      text: 'Measuring gives a random answer each time, with odds set by the ghost. You repeat the experiment until you get the result you want.',
      term: 'This is called probabilistic computation',
      useful: 'Many quantum algorithms are repeated until the right answer shows up. As long as the right answer is likely enough, that works.',
      circuit: 'q0: ─H─M─ ─H─M─ ─H─M─',
    },
  },
  {
    id: 15,
    name: 'Whisper Door',
    chars: [
      'X',
      'H',
      'Z',
      'C',
    ],
    guidance: 'hints',
    map: [
      '################',
      '#P.......M.D...#',
      '########E#####.#',
      '##############.#',
      '#..N.2.........#',
      '#.########.#####',
      '#.##############',
      '#..D..N.....G..#',
      '################',
    ],
    stars: [[4, 1], [12, 1], [10, 5]],
    goal: 'Win the door\'s coin toss, switch to Day to walk through, then reach Night with a half turn.',
    why: 'World and door are entangled until the Eye. Only Night+open lets you in, and the Owl brings Day back while the door stays open.',
    steps: [],
    hints: [
      'Idea: the magic door is a coin toss: Night+open or Day+closed. Then you need Day for the bridge.',
      'Goose, Cat and Owl first. The Octopus later.',
      'H, C next to the door, Eye. If Night+open: X (Day), walk through. Later H Z, gate, H for Night, and X for the last bridges.',
    ],
    card: {
      text: 'Entanglement and single-qubit gates work together: the door told you the world, and the Owl changed the world without touching the door.',
      term: 'This is called combining entanglement with local gates',
      useful: 'Protocols such as quantum teleportation are built exactly like this: entangle, act on one qubit, measure.',
      circuit: 'q0: ─H─●─M─X─\nq1: ───⊕─M───',
    },
  },
  {
    id: 16,
    name: 'Quarter Chain',
    chars: [
      'H',
      'S',
      'Z',
    ],
    guidance: 'hints',
    map: [
      '################',
      '#P..1.3E.N.....#',
      '##############.#',
      '##############.#',
      '#..D..0........#',
      '#.##.###########',
      '#.##############',
      '#.?E.N.....G...#',
      '################',
    ],
    stars: [[9, 1], [12, 1], [4, 5]],
    goal: 'Turn the wheel to colour 1, then 3, win the Eye, then return to Day.',
    why: 'To retry the Eye you have to rebuild the right colour to walk back through the gate. Tracking phase carefully is the whole puzzle.',
    steps: [],
    hints: [
      'Idea: the Eye gate wants colour 3, and you must rebuild it to retry.',
      'Goose and Lizard (the Octopus saves a step).',
      'H S (gate 1), Z or S S (gate 3), Eye. If Day: H, S S S back to colour 3, step back through the gate, Eye.',
    ],
    card: {
      text: 'You managed the phase by hand: one quarter, then three, and back again. Phase must be tracked exactly for the interference to work.',
      term: 'This is called phase control',
      useful: 'On real hardware, keeping phases accurate is one of the hardest engineering problems.',
      circuit: 'q0: ─H─S─Z─M─',
    },
  },
  {
    id: 17,
    name: 'Fork in the Road',
    chars: [
      'X',
      'H',
      'C',
    ],
    guidance: 'hints',
    map: [
      '################',
      '#P...N.........#',
      '########?#####.#',
      '########D#####M#',
      '#..N.E?........#',
      '#.##############',
      '#.##############',
      '#.....D...M.G..#',
      '###.############',
      '################',
    ],
    stars: [[14, 2], [8, 2], [3, 8]],
    goal: 'Take either road: through the door or through the ghost gate. Both lead on.',
    why: 'Different gate sequences can reach the same place. Shorter ones need fewer operations, and on real machines every gate adds noise.',
    steps: [],
    hints: [
      'Idea: two roads, the east door or the middle ghost gate.',
      'Owl first for the bridge. Cat for the door, or Goose for the gate.',
      'X, then C by the door; or X, H, gate, H, bridge. Then Eye and Night bridge, and later the Day bridge.',
    ],
    card: {
      text: 'There was more than one correct circuit. You chose one, and a quantum compiler would choose the shortest.',
      term: 'This is called circuit optimization',
      useful: 'Fewer gates means fewer errors on real quantum hardware, so shorter circuits matter.',
      circuit: 'q0: ─X─●─ or ─X─X─H─H─\nq1: ───⊕─',
    },
  },
  {
    id: 18,
    name: 'Locksmith',
    chars: [
      'X',
      'H',
      'S',
      'C',
    ],
    guidance: 'hints',
    map: [
      '################',
      '#P.......M.D...#',
      '########E#####.#',
      '##############.#',
      '#.....N.E3.1...#',
      '#.##########.###',
      '#.##############',
      '#..0.D......G..#',
      '################',
    ],
    stars: [[4, 1], [12, 1], [12, 5]],
    goal: 'Open the door with the Eye, climb the colour ladder to 1 and 3, win another Eye, then return to Day.',
    why: 'This chains three ideas: entanglement to open the door, phase to build the right colour, and measurement to pick a world.',
    steps: [],
    hints: [
      'Idea: door coin toss first, then colours 1 and 3 with another Eye, then Day.',
      'Goose, Cat, Owl and Lizard.',
      'H, C, Eye (Night+open), X, Day bridge. Then H S (gate 1), S S (gate 3), Eye for Night. Last: H S S (gate 0), H.',
    ],
    card: {
      text: 'You combined entanglement, phase and measurement in one run. That is what real quantum programs do.',
      term: 'This is called a hybrid circuit',
      useful: 'Useful algorithms mix all three ingredients: entangle, interfere with phase, then measure.',
      circuit: 'q0: ─H─●─M─X─H─S─S─S─M─\nq1: ───⊕─M─────────',
    },
  },
  {
    id: 19,
    name: 'Gauntlet',
    chars: [
      'X',
      'H',
      'S',
      'Z',
      'C',
    ],
    guidance: 'hints',
    map: [
      '################',
      '#P..?E.N.......#',
      '########.#####.#',
      '##############.#',
      '#...D.0.M......#',
      '#.####.#########',
      '#.##############',
      '#..?E.N.0.D.G..#',
      '################',
    ],
    stars: [[10, 1], [8, 2], [6, 5]],
    goal: 'Eye, door, colour gate, Day bridge, Eye, colour gate, Day bridge: survive them all.',
    why: 'Everything you learned appears in one corridor. Each section needs the right world and the right colour at the right moment.',
    steps: [],
    hints: [
      'Idea: Eye, then the door at Night, then rebuild Day, then another Eye.',
      'Goose, Cat and Octopus (Lizard and Owl are optional).',
      'H, gate, Eye (Night). C at the door. H Z, gate 0, H (Day). Then H, gate, Eye (Night), H Z, gate 0, H (Day).',
    ],
    card: {
      text: 'Every gate you learned showed up: flip, ghost, phase, link and measurement.',
      term: 'This is called a full quantum workflow: prepare, evolve, measure',
      useful: 'Every quantum algorithm follows the same three steps: prepare a state, let gates evolve it, then measure.',
      circuit: 'q0: ─H─M─●─H─Z─H─H─M─H─Z─H─\nq1: ───────⊕───────────────',
    },
  },
  {
    id: 20,
    name: 'Grand Finale',
    chars: [
      'X',
      'H',
      'S',
      'Z',
      'C',
    ],
    guidance: 'none',
    need: 5,
    map: [
      '################',
      '#P..1.3E.N.....#',
      '############.#.#',
      '##############.#',
      '#...D.0.M......#',
      '#.#.############',
      '#.##############',
      '#..?E.N.0.D.G..#',
      '#########.######',
      '################',
    ],
    stars: [[12, 2], [9, 1], [8, 4], [3, 5], [9, 8]],
    goal: 'Collect all 5 stars and reach the finish.',
    why: 'This last maze uses every mechanic. The stars are hidden off the main road: you need all of them to finish.',
    steps: [],
    hints: [],
    card: {
      text: 'You collected every star and used all five gates. You built the same kind of circuit that real quantum computers run.',
      term: 'This is called a quantum circuit: gates that prepare, evolve and measure qubits',
      useful: 'You now know the vocabulary of quantum computing: superposition, phase, interference, entanglement and measurement.',
      circuit: 'q0: ─H─S─Z─M─●─H─Z─H─H─M─H─Z─H─\nq1: ─────────⊕─────────────────',
    },
  },
];
